<a href="https://colab.research.google.com/github/pratyanch-github/competitive-programming/blob/main/new_python_project.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [23]:
import pandas as pd
df=pd.read_csv("pd_speech_features.csv")
df.head()

id  gender      PPE      DFA     RPDE  numPulses  numPeriodsPulses  \
0   0       1  0.85247  0.71826  0.57227        240               239   
1   0       1  0.76686  0.69481  0.53966        234               233   
2   0       1  0.85083  0.67604  0.58982        232               231   
3   1       0  0.41121  0.79672  0.59257        178               177   
4   1       0  0.32790  0.79782  0.53028        236               235   

   meanPeriodPulses  stdDevPeriodPulses  locPctJitter  ...  \
0          0.008064            0.000087       0.00218  ...   
1          0.008258            0.000073       0.00195  ...   
2          0.008340            0.000060       0.00176  ...   
3          0.010858            0.000183       0.00419  ...   
4          0.008162            0.002669       0.00535  ...   

   tqwt_kurtosisValue_dec_28  tqwt_kurtosisValue_dec_29  \
0                     1.5620                     2.6445   
1                     1.5589                     3.6107   
2                     1.5643                     2.3308   
3                     3.7805                     3.5664   
4                     6.1727                     5.8416   

   tqwt_kurtosisValue_dec_30  tqwt_kurtosisValue_dec_31  \
0                     3.8686                     4.2105   
1                    23.5155                    14.1962   
2                     9.4959                    10.7458   
3                     5.2558                    14.0403   
4                     6.0805                     5.7621   

   tqwt_kurtosisValue_dec_32  tqwt_kurtosisValue_dec_33  \
0                     5.1221                     4.4625   
1                    11.0261                     9.5082   
2                    11.0177                     4.8066   
3                     4.2235                     4.6857   
4                     7.7817                    11.6891   

   tqwt_kurtosisValue_dec_34  tqwt_kurtosisValue_dec_35  \
0                     2.6202                     3.0004   
1                     6.5245                     6.3431   
2                     2.9199                     3.1495   
3                     4.8460                     6.2650   
4                     8.2103                     5.0559   

   tqwt_kurtosisValue_dec_36  class  
0                    18.9405      1  
1                    45.1780      1  
2                     4.7666      1  
3                     4.0603      1  
4                     6.1164      1  

[5 rows x 755 columns]

In [24]:
#data processing


x=df.drop('class', axis=1)
#x=df.drop('name', axis=1)
y=df['class']

In [25]:
#data splitting 
from sklearn.model_selection import train_test_split

x_train, x_test, y_train, y_test = train_test_split(
    x, y, test_size=0.2, random_state=42)

In [27]:
#model building 
from sklearn.ensemble import RandomForestClassifier

rf = RandomForestClassifier(n_estimators=10)
rf.fit(x_train, y_train)


RandomForestClassifier(n_estimators=10)

score() is used for evaluating the quality of a model’s predictions

predict() is used to predict the output for a given input

In [28]:
# Prediction before k folds
# 1. random forest

y_rf_train_pred = rf.predict(x_train)
y_rf_test_pred = rf.predict(x_test)
# print(y_rf_test_pred)
# print(y_test)

rf.score(x_test, y_test)

0.8223684210526315

In [29]:
# 2. logistic regresstion 

from sklearn.linear_model import LogisticRegression
lr = LogisticRegression(solver='liblinear',multi_class='ovr')
lr.fit(x_train, y_train)
lr.score(x_test, y_test)

0.75

In [31]:
# 3. support vector machine

from sklearn.svm import SVC
svm = SVC(gamma='auto')
svm.fit(x_train, y_train)
svm.score(x_test, y_test)

0.75

In [6]:
# claculating errors

from sklearn.metrics import mean_squared_error, r2_score
rf_train_mse = mean_squared_error(y_train, y_rf_train_pred)
rf_train_r2 = r2_score(y_train, y_rf_train_pred)
rf_test_mse = mean_squared_error(y_test, y_rf_test_pred)
rf_test_r2 = r2_score(y_test, y_rf_test_pred)

In [39]:
from sklearn.model_selection import cross_val_score
import numpy as np

# 5 folds with logistic regression
score_lr=cross_val_score(LogisticRegression(solver='liblinear',multi_class='ovr'), x, y,cv=5)
print(score_lr)
print("score of logistic regression after cross validation ")
print("Avg :",np.average(score_lr))
print("")


score_rf=cross_val_score(RandomForestClassifier(n_estimators=10),x, y,cv=5)
print(score_rf)
print("score of random forest after cross validation ")
print("Avg :",np.average(score_rf))
print("")

score_svm =cross_val_score(SVC(gamma='auto'), x, y,cv=5)
print(score_svm)
print("score of support vector machine after cross validation ")
print('Avg :',np.average(score_svm))

[0.76315789 0.8013245  0.76821192 0.8013245  0.72847682]
score of logistic regression after cross validation 
Avg : 0.7724991286162426

[0.80921053 0.79470199 0.8013245  0.8410596  0.75496689]
score of random forest after cross validation 
Avg : 0.8002527012896479

[0.74342105 0.74834437 0.74834437 0.74834437 0.74172185]
score of support vector machine after cross validation 
Avg : 0.7460352039037993
